### PR TITLE
Enable the ability to import templates from playbooks.

### PR DESCRIPTION
**Pull request by tinyroy**

### CODE REVIEW

**Comment by colstrom** [comment]
This change overlaps with functionality already present in Forge. Consider doing this instead:

In `dependencies.yml`

``` yaml
- src: git@github.com:telusdigital/project-foo
  name: project.foo
  scm: git
```

and it will pull down templates and everything else.

Then just include that in `playbook.yml` like so:

``` yaml
roles:
- role: project.foo
```

**Comment by tinyroy** [comment]
Thanks for the input Olstrom.

We have tried this but it causes dependency issues, where it tries to use a role before it is downloaded.

I also consider this as a hack since it is trying to include a project playbook as a role.

**Comment by colstrom** [comment]
When your playbook has supporting files (such as templates), it (for all practical purposes) _is_ a role.

In `self_provision()` dependencies are _always_ fetched before a playbook is executed. If there is a scenario where `execute(playbook)` is invoked before `get_dependencies(playbook)`, this would be a bug in Forge.

Can you provide steps to reproduce that issue? That's a potentially serious bug that should be investigated.

**Comment by tinyroy** [comment]
I think that's where I disagree with you. A project playbook that is not reusable is not a role.
A project playbook that include itself as a dependency is hacky.
The dependency problem of including itself as a role comes from ansible, not forge.

**Comment by stevenharradine** [comment]
whats the use case? can i see an example and i can try to present an alternative using chris's method  I think thats cleaner and keeps forge simpler.

**Comment by killerwails-zz** [comment]
From what I understand `/tmp` is supposed to be a safe place to write to. By avoiding directories, we don't have to worry about all the  checks and error conditions around directories existing or not. Also permissions. And that the data being written was ephemeral.
This ensured that every run would run the latest code, and only the latest code.
Now there's a whole bunch of ways forge can be run with different effects to each and the potential for bugs to hide and only be seen in certain conditions.

**Comment by killerwails-zz** [comment]
We should ask not if we can add the functionality, but should we? I believe this change will deviate greatly from what Forge was originally created to do.
For example, the purpose of `flat_path` function was to keep things simple.
The proposed replacement seems to now have two exit paths, with one of three side-effects. This adds unnecessary complexity to this program. Forge is meant to be stupid and simply run playbooks.

**Comment by tinyroy** [comment]
Thanks for the input @killerwails. I do agree that directory management is a bit more work but nothing new to python scripts. The new arguments are for increasing our testing and development processes, something that we desperately need. The arguments are not meant for reforging.

I believe this is the cleanest and simplest way to include templates with the playbook.

**Comment by lucidaeon** [comment]
I think this warrants a larger discussion as a team regarding differences between:
the original vision for forge
our current usage
the current vision, continuing the original vision, or pivoting

With our fork undergoing changes, I think the most important thing we need to do right now is tag a known good recent version as v0.0.1 that way projects can rely on that. Moving forward, we need a strategy so that changes imposed by various projects do not affect others. Perhaps forking or create per-project branches so that projects can have an evolving forge codebase if required.

For the record, @colstrom what was your original vision for forge? Can you go in to a bit of detail about Convention Driven Instance Autonomy?

**Comment by colstrom** [comment]
@laurentr Absolutely.

The original vision for `forge` was to minimize human interaction with systems, especially in the context of provisioning. Taking the following as givens:
- Roles and playbooks deployed to production areas (master branches, buckets, etc) are in a known-good state.
- Instances are provisioned in a consistent manner, with some metadata describing their purpose.

A newly-provisioned system is able to accurately determine its purpose, and configure itself into a known-good state without an operator. This ensures minimal differences between dev/stage/prod systems, and provides a reliable mechanism to (re)establish a known-good state, or duplicate an environment in the event that troubleshooting is required.

A critical part of this was standardization. Not in the "everything runs the same stack" sense, but the "the same set of roles with the same configuration parameters will yield an equivalent and testable system" sense. Strictly speaking, this was and is outside the scope of `forge`, but the approach taken in the roles is an influencing factor in how `forge` is intended to work, and so is relevant here.

The endgame was fully autonomous deployments. Publishing a new `project-*` repository would trigger infrastructure provisioning according to that repo's `infrastructure.yml`, either creating or updating as needed. Pushing a change to an `ansible-*` repository would trigger any systems using that role to `reforge`, pulling and running the latest versions of that role. Pushing application code to a repository would deploy to the appropriate environment. Branches provide isolation of changes across environments, and automated acceptance tests could provide the confidence behind automated promotions to `develop` or `master`. This is why `aws-infrastructure` assumes some of the things it does (like how routes not defined in the role or playbook should be purged). Having the confidence that "as it is written, so it stands" if a playbook runs to completion without failure.

This means less room for human error, and more effective understanding and troubleshooting for an Ops team. "Seeing an issue with SSL. Only flag set is `nginx_ssl_enabled`, that's known good. Can spawn a test system with the same flag trivially if additional testing is required."

It dramatically reduced the cognitive load of troubleshooting, and meant that behaviour could be implemented once, and made available to all projects using that software package through a flag. Improved momentum for both Devs and Ops.

So the emphasis on flags to encapsulate behaviour variations in roles is one of the big reasons why forge does not import templates by default. It encourages the use of flags over unique per-project configuration. This in turn emphasizes reusable behaviour in roles, which keeps the system maintainable by a small team.

If there are any particulars you're curious about, I'd be happy to address them.

**Comment by pdufault** [comment]
Enabling forge to download templates at a role and project level allows us to utilize more of Ansible's basic playbook functionality.

After a lengthy meeting amongst the infrastructure team here at TELUS digital, we've decided to accept and merge this contribution, as we want to enable our colleagues to collaborate with us with a low barrier to entry.

I've done some testing of this branch, and works as expected.

Thanks for everyone's thoughts for weighing in here on this pull request.

We'll merge this in tomorrow during our usual review cycle.

**Comment by aaronpederson** [comment]
Team Approved

**Pull request merged**
